class Pinviz < Formula
  include Language::Python::Virtualenv

  desc "Generate Raspberry Pi GPIO wiring diagrams from YAML/JSON configs"
  homepage "https://nordstad.github.io/PinViz/"
  url "https://files.pythonhosted.org/packages/79/94/0d8b0601e06c38ce6743eeaf72a737221dfed76fc28e180b87dc1c8dd03d/pinviz-0.17.0.tar.gz"
  sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  license "MIT"

  depends_on "rust" => :build # required for pydantic-core and rpds-py
  depends_on "python@3.13"

  # --- resource stanzas (generated by: brew update-python-resources Formula/pinviz.rb) ---

  resource "annotated-doc" do
    url "https://files.pythonhosted.org/packages/57/ba/046ceea27344560984e26a590f90bc7f4a75b06701f653222458922b558c/annotated_doc-0.0.4.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "annotated-types" do
    url "https://files.pythonhosted.org/packages/ee/67/531ea369ba64dcff5ec9c3402f9f51bf748cec26dde048a2f973a4eea7f5/annotated_types-0.7.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "anyio" do
    url "https://files.pythonhosted.org/packages/c6/78/7d432127c41b50bccba979505f272c16cbcadcc33645d5fa3a738110ae75/anyio-4.11.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "attrs" do
    url "https://files.pythonhosted.org/packages/6b/5c/685e6633917e101e5dcb62b9dd76946cbb57c26e133bae9e0cd36033c0a9/attrs-25.4.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "beautifulsoup4" do
    url "https://files.pythonhosted.org/packages/c3/b0/1c6a16426d389813b48d95e26898aff79abbde42ad353958ad95cc8c9b21/beautifulsoup4-4.14.3.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "certifi" do
    url "https://files.pythonhosted.org/packages/a2/8c/58f469717fa48465e4a50c014a0400602d3c437d7c0c468e17ada824da3a/certifi-2025.11.12.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "cffi" do
    url "https://files.pythonhosted.org/packages/eb/56/b1ba7935a17738ae8453301356628e8147c79dbb825bcbc73dc7401f9846/cffi-2.0.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/3d/fa/656b739db8587d7b5dfa22e22ed02566950fbfbcdc20311993483657a5c0/click-8.3.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "colorama" do
    url "https://files.pythonhosted.org/packages/d8/53/6f443c9a4a8358a93a6792e2acffb9d9d5cb0a5cfd8802644b7b1c9a02e4/colorama-0.4.6.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "cryptography" do
    url "https://files.pythonhosted.org/packages/60/04/ee2a9e8542e4fa2773b81771ff8349ff19cdd56b7258a0cc442639052edb/cryptography-46.0.5.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  # drawsvg is pure Python and ships wheels only; reference the wheel directly
  resource "drawsvg" do
    url "https://files.pythonhosted.org/packages/bf/07/a2c3db84e6af6fa761de905b39109fe24eff2c8d52653c1bff968b6b965d/drawsvg-2.4.1-py3-none-any.whl"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "h11" do
    url "https://files.pythonhosted.org/packages/01/ee/02a2c011bdab74c6fb3c75474d40b3052059d95df7e73351460c8588d963/h11-0.16.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "httpcore" do
    url "https://files.pythonhosted.org/packages/06/94/82699a10bca87a5556c9c59b5963f2d039dbd239f25bc2a63907a05a14cb/httpcore-1.0.9.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "httpx" do
    url "https://files.pythonhosted.org/packages/b1/df/48c586a5fe32a0f01324ee087459e112ebb7224f646c0b5023f5e79e9956/httpx-0.28.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "httpx-sse" do
    url "https://files.pythonhosted.org/packages/0f/4c/751061ffa58615a32c31b2d82e8482be8dd4a89154f003147acee90f2be9/httpx_sse-0.4.3.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/6f/6d/0703ccc57f3a7233505399edb88de3cbd678da106337b9fcde432b65ed60/idna-3.11.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "jsonschema" do
    url "https://files.pythonhosted.org/packages/74/69/f7185de793a29082a9f3c7728268ffb31cb5095131a9c139a74078e27336/jsonschema-4.25.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "jsonschema-specifications" do
    url "https://files.pythonhosted.org/packages/19/74/a633ee74eb36c44aa6d1095e7cc5569bebf04342ee146178e2d36600708b/jsonschema_specifications-2025.9.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/5b/f5/4ec618ed16cc4f8fb3b701563655a69816155e79e24a17b651541804721d/markdown_it_py-4.0.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "mcp" do
    url "https://files.pythonhosted.org/packages/fc/6d/62e76bbb8144d6ed86e202b5edd8a4cb631e7c8130f3f4893c3f90262b10/mcp-1.26.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/d6/54/cfe61301667036ec958cb99bd3efefba235e65cdeb9c84d24a8293ba1d90/mdurl-0.1.2.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "platformdirs" do
    url "https://files.pythonhosted.org/packages/19/56/8d4c30c8a1d07013911a8fdbd8f89440ef9f08d07a1b50ab8ca8be5a20f9/platformdirs-4.9.4.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "prompt-toolkit" do
    url "https://files.pythonhosted.org/packages/a1/96/06e01a7b38dce6fe1db213e061a4602dd6032a8a97ef6c1a862537732421/prompt_toolkit-3.0.52.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pycparser" do
    url "https://files.pythonhosted.org/packages/fe/cf/d2d3b9f5699fb1e4615c8e32ff220203e43b248e1dfcc6736ad9057731ca/pycparser-2.23.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pydantic" do
    url "https://files.pythonhosted.org/packages/69/44/36f1a6e523abc58ae5f928898e4aca2e0ea509b5aa6f6f392a5d882be928/pydantic-2.12.5.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pydantic-core" do
    url "https://files.pythonhosted.org/packages/71/70/23b021c950c2addd24ec408e9ab05d59b035b39d97cdc1130e1bce647bb6/pydantic_core-2.41.5.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pydantic-settings" do
    url "https://files.pythonhosted.org/packages/52/6d/fffca34caecc4a3f97bda81b2098da5e8ab7efc9a66e819074a11955d87e/pydantic_settings-2.13.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/b0/77/a5b8c569bf593b0140bde72ea885a803b82086995367bf2037de0159d924/pygments-2.19.2.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pyjwt" do
    url "https://files.pythonhosted.org/packages/a8/10/e8192be5f38f3e8e7e046716de4cae33d56fd5ae08927a823bb916be36c1/pyjwt-2.12.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "python-dotenv" do
    url "https://files.pythonhosted.org/packages/f0/26/19cadc79a718c5edbec86fd4919a6b6d3f681039a2f6d66d14be94e75fb9/python_dotenv-1.2.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "python-multipart" do
    url "https://files.pythonhosted.org/packages/94/01/979e98d542a70714b0cb2b6728ed0b7c46792b695e3eaec3e20711271ca3/python_multipart-0.0.22.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "questionary" do
    url "https://files.pythonhosted.org/packages/f6/45/eafb0bba0f9988f6a2520f9ca2df2c82ddfa8d67c95d6625452e97b204a5/questionary-2.1.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "referencing" do
    url "https://files.pythonhosted.org/packages/22/f5/df4e9027acead3ecc63e50fe1e36aca1523e1719559c499951bb4b53188f/referencing-0.37.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/b3/c6/f3b320c27991c46f43ee9d856302c70dc2d0fb2dba4842ff739d5f46b393/rich-14.3.3.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "rpds-py" do
    url "https://files.pythonhosted.org/packages/98/33/23b3b3419b6a3e0f559c7c0d2ca8fc1b9448382b25245033788785921332/rpds_py-0.29.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "shellingham" do
    url "https://files.pythonhosted.org/packages/58/15/8b3609fd3830ef7b27b655beb4b4e9c62313a4e8da8c676e142cc210d58e/shellingham-1.5.4.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "sniffio" do
    url "https://files.pythonhosted.org/packages/a2/87/a6771e1546d97e7e041b6ae58d80074f81b7d5121207425c964ddf5cfdbd/sniffio-1.3.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "soupsieve" do
    url "https://files.pythonhosted.org/packages/6d/e6/21ccce3262dd4889aa3332e5a119a3491a95e8f60939870a3a035aabac0d/soupsieve-2.8.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "sse-starlette" do
    url "https://files.pythonhosted.org/packages/db/3c/fa6517610dc641262b77cc7bf994ecd17465812c1b0585fe33e11be758ab/sse_starlette-3.0.3.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "starlette" do
    url "https://files.pythonhosted.org/packages/ba/b8/73a0e6a6e079a9d9cfa64113d771e421640b6f679a52eeb9b32f72d871a1/starlette-0.50.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "structlog" do
    url "https://files.pythonhosted.org/packages/ef/52/9ba0f43b686e7f3ddfeaa78ac3af750292662284b3661e91ad5494f21dbc/structlog-25.5.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "typer" do
    url "https://files.pythonhosted.org/packages/f5/24/cb09efec5cc954f7f9b930bf8279447d24618bb6758d4f6adf2574c41780/typer-0.24.1.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "typing-extensions" do
    url "https://files.pythonhosted.org/packages/72/94/1a15dd82efb362ac84269196e94cf00f187f7ed21c242792a923cdb1c61f/typing_extensions-4.15.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "typing-inspection" do
    url "https://files.pythonhosted.org/packages/55/e3/70399cb7dd41c10ac53367ae42139cf4b1ca5f36bb3dc6c9d33acdb43655/typing_inspection-0.4.2.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "uvicorn" do
    url "https://files.pythonhosted.org/packages/cb/ce/f06b84e2697fef4688ca63bdb2fdf113ca0a3be33f94488f2cadb690b0cf/uvicorn-0.38.0.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  resource "wcwidth" do
    url "https://files.pythonhosted.org/packages/24/30/6b0809f4510673dc723187aeaf24c7f5459922d01e2f794277a3dfb90345/wcwidth-0.2.14.tar.gz"
    sha256 "bdf21c125c33544cb6d65eec2e57f8ebcb96c3733ff42203b9b97d74c2f345f4"
  end

  def install
    virtualenv_install_with_resources

    # Typer's --show-completion relies on shellingham to detect the parent shell,
    # which fails in a build sandbox. Generate completion scripts via Typer's
    # Python API directly to avoid that dependency on process introspection.
    py = libexec/"bin/python"
    {
      bash_completion/"pinviz"      => "bash",
      zsh_completion/"_pinviz"      => "zsh",
      fish_completion/"pinviz.fish" => "fish",
    }.each do |path, shell|
      path.write Utils.safe_popen_read(
        py, "-c",
        "from typer.completion import get_completion_script; " \
        "print(get_completion_script(" \
        "prog_name='pinviz', complete_var='_PINVIZ_COMPLETE', shell='#{shell}'))"
      )
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pinviz --version")
  end
end
